apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-frontend
  namespace: argocd
  labels:
    project: demo-project
    tier: frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gh-gitops-infra.git
    targetRevision: HEAD
    path: manifiestos/demo-project/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
