apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 2.4.8
    chart: argo-events
    helm:
      values: |
        # CONFIGURACIÓN MÍNIMA PARA DEV - Single replica
        controller:
          enabled: true
          replicas: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # Webhook simplificado
        webhook:
          enabled: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 32Mi
        
        # Deshabilitar métricas para dev
        serviceMonitor:
          enabled: false
          
        # Deshabilitar RBAC cluster-wide para dev
        createAggregateRoles: false
        
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
