apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.2  # Chart version correcta (app version v1.8.3)
    helm:
      values: |
        # CONFIGURACIÓN MÍNIMA PARA DEV
        controller:
          replicas: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
        # Dashboard simplificado para dev
        dashboard:
          enabled: true
          readonly: false
          service:
            type: ClusterIP
            port: 3100
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 32Mi
          # Sin autenticación para desarrollo
          config:
            auth:
              enabled: false
              
        # Deshabilitar métricas para dev
        serviceMonitor:
          enabled: false
            
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  # Add this block to ignore the specific, harmless difference in the CRDs.
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
    - SkipDryRunOnMissingResource=true
