apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.18.2
    helm:
      values: |
        # CONFIGURACIÓN MÍNIMA PARA DEV
        installCRDs: true
        
        # Webhook simplificado para dev
        webhook:
          enabled: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 32Mi
        
        # Cert-controller reducido
        certController:
          enabled: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 32Mi
        
        # Resources mínimos para controlador
        resources:
          limits:
            cpu: 150m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
        
        # Deshabilitar métricas para dev
        serviceMonitor:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
