apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "PrunePropagationPolicy=foreground"
spec:
  project: default
  source:
    repoURL: https://dl.gitea.io/charts/
    chart: gitea
    targetRevision: 12.1.2
    helm:
      values: |
        # CONFIGURACIÓN MÍNIMA PARA DEV - SINGLE POD con SQLite
        gitea:
          admin:
            username: admin
            password: admin123
            email: admin@gitea.local
          config:
            database:
              DB_TYPE: sqlite3
              PATH: /data/gitea/gitea.db
        
        # Service básico
        service:
          http:
            type: ClusterIP
            port: 3000
        
        # Sin ingress
        ingress:
          enabled: false
        
        # Persistencia mínima
        persistence:
          enabled: true
          size: 5Gi
        
        # PostgreSQL DESHABILITADO (SQLite)
        postgresql:
          enabled: false
          
        # PostgreSQL-HA DESHABILITADO (causa de los problemas pgpool)
        postgresql-ha:
          enabled: false
          
        # Valkey-cluster DESHABILITADO (habilitado por defecto en el chart)
        valkey-cluster:
          enabled: false
          
        # Valkey DESHABILITADO  
        valkey:
          enabled: false
        
        # Resources mínimos
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  
  # Configuración de sincronización
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
