apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Repositorio OCI oficial de Kargo - según documentación oficial
    repoURL: ghcr.io/akuity/kargo-charts
    chart: kargo
    targetRevision: 1.0.8
    helm:
      values: |
        # Configuración simplificada para desarrollo siguiendo docs oficiales
        api:
          adminAccount:
            enabled: true
            # Password: admin123 (usando bcrypt hash oficial de los ejemplos)
            passwordHash: "$$2a$$10$$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm"
            # Token signing key del quickstart oficial
            tokenSigningKey: "iwishtowashmyirishwristwatch"
            tokenTTL: 24h
          service:
            type: ClusterIP
            port: 8080
          # Recursos mínimos para desarrollo
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          
        # Controller simplificado según docs
        controller:
          replicas: 1
          logLevel: INFO
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # Integración ArgoCD habilitada - namespace correcto
          argocd:
            integrationEnabled: true
            namespace: argocd
            watchArgocdNamespaceOnly: false
          # Integración Argo Rollouts habilitada
          rollouts:
            integrationEnabled: true
            
        # Webhooks server simplificado
        webhooksServer:
          replicas: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
