apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Repositorio OCI oficial según documentación Kargo
    chart: kargo
    repoURL: oci://ghcr.io/akuity/kargo-charts
    targetRevision: v1.0.8
    helm:
      values: |
        # Configuración simplificada para desarrollo siguiendo documentación oficial
        api:
          enabled: true
          replicas: 1
          logLevel: INFO
          adminAccount:
            enabled: true
            # Password: admin123 (hash oficial de los ejemplos de quickstart)
            passwordHash: "$2a$10$Zrhhie4vLz5ygtVSaif6o.qN36jgs6vjtMBdM6yrU1FOeiAAMMxOm"
            # Token signing key del quickstart oficial
            tokenSigningKey: "iwishtowashmyirishwristwatch"
            tokenTTL: 24h
          service:
            type: ClusterIP
            port: 8080
          # Recursos mínimos para desarrollo
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # TLS simplificado para desarrollo
          tls:
            enabled: true
            selfSignedCert: true
            
        # Controller principal con integración ArgoCD
        controller:
          enabled: true
          logLevel: INFO
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # Integración ArgoCD oficial
          argocd:
            integrationEnabled: true
            namespace: argocd
            watchArgocdNamespaceOnly: false
          # Integración Argo Rollouts oficial
          rollouts:
            integrationEnabled: true
            
        # Management Controller
        managementController:
          enabled: true
          logLevel: INFO
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
            
        # Webhooks Server simplificado
        webhooksServer:
          enabled: true
          replicas: 1
          logLevel: INFO
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # External Webhooks Server simplificado
        externalWebhooksServer:
          enabled: true
          replicas: 1
          logLevel: INFO
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # Garbage Collector simplificado
        garbageCollector:
          enabled: true
          logLevel: INFO
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
