apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-infra-app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gh-gitops-infra.git
    targetRevision: HEAD
    path: componentes
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
