apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-infra-components
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/andres20980/gh-gitops-infra.git
      revision: HEAD
      directories:
      - path: componentes/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gh-gitops-infra.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
---
# ApplicationSet para proyectos de aplicaciones  
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-projects
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: https://github.com/andres20980/gh-gitops-infra.git
      revision: HEAD
      files:
      - path: "proyectos/*/app-of-apps.yaml"
  template:
    metadata:
      name: '{{path[1]}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/andres20980/gh-gitops-infra.git
        targetRevision: HEAD
        path: '{{path[0]}}/{{path[1]}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
