apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-notifications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argocd-notifications
    targetRevision: 1.8.1  # Latest version from helm search
    helm:
      # Optimized values for GitOps development environment
      values: |
        # Controller configuration
        controller:
          replicas: 1
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
        
        # Global settings
        global:
          image:
            tag: v1.2.1
        
        # RBAC
        rbac:
          enabled: true
        
        # Service Account
        serviceAccount:
          create: true
          name: argocd-notifications
        
        # Configuration for notifications
        config:
          # Basic email configuration (can be customized later)
          service.email.gmail: |
            username: $gmail-username
            password: $gmail-password
            host: smtp.gmail.com
            port: 587
            from: $gmail-username
          
          # Basic webhook configuration
          service.webhook.generic: |
            url: http://localhost:8080/webhook
            headers:
            - name: Content-Type
              value: application/json
        
        # Secret for credentials (empty for now)
        secret:
          create: true
          annotations: {}
          labels: {}
          
        # Metrics
        metrics:
          enabled: true
          service:
            type: ClusterIP
            port: 9001
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd  # Notifications usually go in the same namespace as ArgoCD
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
