apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.4.16  # Latest version from helm search
    helm:
      # Optimized values for GitOps development environment
      values: |
        # Controller configuration
        controller:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
        
        # Global settings
        global:
          image:
            tag: v1.9.7
        
        # RBAC enabled
        rbac:
          enabled: true
        
        # Service Account
        serviceAccount:
          create: true
          name: argo-events
        
        # Configurations
        configs:
          # EventBus default configuration
          eventBus:
            nats:
              native:
                replicas: 1
                auth: none
                persistence:
                  storageClassName: standard
                  accessMode: ReadWriteOnce
                  volumeSize: 1Gi
                resources:
                  requests:
                    memory: "64Mi"
                    cpu: "50m"
                  limits:
                    memory: "128Mi"
                    cpu: "100m"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
