# Configuración optimizada para desarrollo - argo-rollouts
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
replicaCount: 1
dashboard:
  enabled: true
  service:
    type: ClusterIP
    port: 3100
installCRDs: false
