# Configuración optimizada para desarrollo - Grafana
adminUser: admin
adminPassword: admin123
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
persistence:
  enabled: true
  size: 1Gi
testFramework:
  enabled: false
serviceMonitor:
  enabled: false
