# Configuración optimizada para desarrollo - Jaeger
provisionDataStore:
  cassandra: false
  elasticsearch: false
allInOne:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
storage:
  type: memory
agent:
  enabled: false
collector:
  enabled: false
query:
  enabled: false
