# Configuración optimizada para desarrollo - jaeger
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
replicaCount: 1

# Asegurar servicio de Query para UI
query:
  service:
    type: ClusterIP
    port: 80
