# Configuración optimizada para desarrollo - kargo
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
replicaCount: 1

# Exponer API/UI de Kargo para entorno local
api:
  enabled: true
  service:
    type: ClusterIP
    port: 80
ui:
  enabled: true
