# Configuración optimizada para desarrollo - loki
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
replicaCount: 1
service:
  enabled: true
  type: ClusterIP
  port: 3100

# Configuración mínima para Loki con filesystem en entorno local
loki:
  # Imagen explícita para evitar valores nil en helpers
  image:
    repository: grafana/loki
    tag: "2.9.6"
  # for chart 5.x, ensure single binary mode
deploymentMode: SingleBinary
singleBinary:
  replicas: 1
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
  # Evitar el bloque commonConfig que dispara helpers con bucketNames
  storage_config:
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
  schema_config:
    configs:
      - from: 2020-10-24
        store: boltdb-shipper
        object_store: filesystem
        schema: v13
        index:
          prefix: index_
          period: 24h
  ruler:
    storage:
      type: local
      local:
        directory: /var/loki/rules

persistence:
  enabled: false

# Desactivar dashboards/monitoring para simplificar en dev
monitoring:
  dashboards:
    enabled: false
  serviceMonitor:
    enabled: false
