# Configuración optimizada para desarrollo - minio
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
mode: standalone
replicas: 1
persistence:
  enabled: false
