apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kargo
    repoURL: https://charts.akuity.io
    targetRevision: 1.6.1
    helm:
      values: |
        # Configuración del servidor API de Kargo
        api:
          # Habilitar cuenta admin con credenciales fijas para desarrollo
          adminAccount:
            enabled: true
            username: admin
            password: admin
            # Hash del password "admin" (bcrypt)
            passwordHash: "$2a$10$Ak6eS6.o2cUU7TSjdF.EM.WRb/QhxhT6d4v9kP2GXW6YjGYd4/uTC"
          # Configuración para acceso básico con admin/admin
          oidc:
            enabled: false
          service:
            type: ClusterIP
          
        # Configuración del controlador
        controller:
          replicas: 1
          
        # Configuración del controlador de gestión
        managementController:
          replicas: 1
          
        # Configuración del servidor de webhooks
        webhooksServer:
          replicas: 1
          
        # Configuración del servidor de webhooks externos
        externalWebhooksServer:
          replicas: 1
          service:
            type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
