apiVersion: v1
kind: Secret
metadata:
  name: kargo-oci-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: kargo-charts-kargo
  url: oci://ghcr.io/akuity/kargo-charts/kargo
  enableOCI: "true"
