apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kargo
    repoURL: ghcr.io/akuity/kargo-charts
    targetRevision: 1.6.1
    helm:
      values: |
        # Configuración del servidor API de Kargo
        api:
          # Deshabilitar cuenta admin para acceso sin autenticación
          adminAccount:
            enabled: false
          # Configuración para acceso sin autenticación
          oidc:
            enabled: false
          # Deshabilitar autenticación completamente
          auth:
            enabled: false
          service:
            type: ClusterIP
          
        # Configuración del controlador
        controller:
          replicas: 1
          
        # Configuración del controlador de gestión
        managementController:
          replicas: 1
          
        # Configuración del servidor de webhooks
        webhooksServer:
          replicas: 1
          
        # Configuración del servidor de webhooks externos
        externalWebhooksServer:
          replicas: 1
          service:
            type: ClusterIP

  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
