apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://dl.gitea.io/charts
      chart: gitea
      targetRevision: "12.1.3"
      helm:
        valueFiles:
          - $values/herramientas-gitops/values-dev/gitea-dev-values.yaml
    # El repositorio para los values debe apuntar a la misma fuente de verdad (Gitea local).
    # Este placeholder será sustituido automáticamente en la fase de bootstrap.
    - repoURL: http://gitea-service/your-user/your-repo.git
      targetRevision: HEAD
      ref: values
      path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true


