apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://dl.gitea.io/charts
      chart: gitea
      targetRevision: "12.1.3"
      helm:
        values: |
          image:
            repository: gitea/gitea
            tag: 1.24.3-rootless
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          podSecurityContext:
            fsGroup: 1000
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
          replicaCount: 1
          # Evitar dependencias pesadas: usar SQLite y sin redis/postgres
          persistence:
            enabled: false
          postgresql-ha:
            enabled: false
          postgresql:
            enabled: false
          redis-cluster:
            enabled: false
          valkey:
            enabled: false
          gitea:
            admin:
              username: "admin"
              password: "admin1234"
            config:
              server:
                DISABLE_SSH: true
              service:
                REQUIRE_SIGNIN_VIEW: false
              repository:
                DEFAULT_PRIVATE: public
                ALLOW_ANONYMOUS_GIT_ACCESS: true
                DISABLE_HTTP_GIT: false
              database:
                DB_TYPE: sqlite3
                PATH: /data/gitea/gitea.db
              cache:
                ADAPTER: memory
              session:
                PROVIDER: memory
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true


