apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea-http-stable.gitea.svc.cluster.local:3000/admin/gitops-infra.git
    targetRevision: HEAD
    path: herramientas-gitops/empty
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true


