apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.0
    helm:
      values: |
        controller:
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          # Enable for minikube
          hostPort:
            enabled: false
          # Metrics for monitoring
          metrics:
            enabled: true
            serviceMonitor:
              enabled: true
          # Additional configuration for development
          config:
            use-forwarded-headers: "true"
            compute-full-forwarded-for: "true"
        
        # Enable default backend for better error handling  
        defaultBackend:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
