apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitops-aplicaciones
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - git:
      repoURL: http://gitea-service/your-user/your-repo.git # CAMBIAR: URL del repositorio Gitea local
      revision: HEAD
      directories:
      - path: aplicaciones/*
  template:
    metadata:
      name: 'app-{{path.basename}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: http://gitea-service/your-user/your-repo.git # CAMBIAR: URL del repositorio Gitea local
        targetRevision: HEAD
        path: '{{path}}'
        directory:
          recurse: false
          include: 'aplicacion-de-aplicaciones.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
