apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitea-webhook
  namespace: argo-events
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    # Gitea push events
    gitea-push:
      port: "12000"
      endpoint: /gitea
      method: POST
      # Gitea webhook signature verification
      # url: http://argo-events-webhook.argo-events.svc.cluster.local:12000/gitea
      
      # Event filters para procesar solo ciertos repos/branches
      filter:
        expression: "(body.repository.name == 'demo-project' || body.repository.name == 'gh-gitops-infra') && (body.ref == 'refs/heads/main' || body.ref == 'refs/heads/develop')"
      
      # Data mapping para ArgoCD
      data:
        - src:
            dependencyName: gitea-push
            dataKey: body
          dest: payload
    
    # Generic webhook para otros servicios
    generic-webhook:
      port: "12000"
      endpoint: /webhook  
      method: POST
      
    # Health check endpoint
    health-check:
      port: "12000"
      endpoint: /health
      method: GET
