apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-backend
  namespace: argocd
  labels:
    project: demo-project
    tier: backend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: http://gitea-service/your-user/your-repo.git # CAMBIAR: URL del repositorio Gitea local
    targetRevision: HEAD
    path: aplicaciones/proyecto-demostracion/manifests/backend
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-project
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
  revisionHistoryLimit: 3
