apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-project
  namespace: argocd
  labels:
    project: demo-project
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gh-gitops-infra.git
    targetRevision: HEAD
    path: projects/demo-project/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
