apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.4.16
    helm:
      valueFiles:
        - values-dev/argo-events-dev-values.yaml
      values: |
        # === CONFIGURACIÓN MÍNIMA PARA DESARROLLO ===
        
        controller:
          replicaCount: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
          metrics:
            enabled: false
          
          securityContext:
            runAsNonRoot: true
            runAsUser: 9731
            
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
