apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.3
    helm:
      values: |
        # === CONFIGURACIÓN MÍNIMA PARA DESARROLLO ===
        
        replicaCount: 1
        
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        
        metrics:
          enabled: false
        
        dashboard:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
