apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.21
    helm:
      values: |
        # === CONFIGURACIÓN MÍNIMA PARA DESARROLLO ===
        
        controller:
          replicas: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
          securityContext:
            runAsNonRoot: true
            runAsUser: 8737
          
          metricsConfig:
            enabled: false
        
        server:
          enabled: true
          replicas: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: argo-workflows.local
                paths:
                  - path: /
                    pathType: Prefix
          
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
