apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.21  # Chart version correcta (app version v3.7.0)
    helm:
      values: |
        # CONFIGURACIÓN MÍNIMA PARA DEV
        server:
          enabled: true
          serviceType: ClusterIP
          servicePort: 2746
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          # Sin autenticación para desarrollo
          extraArgs:
          - --auth-mode=server
          - --secure=false
        
        controller:
          enabled: true
          replicas: 1
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 64Mi
          # Solo namespace propio para dev
          workflowNamespaces:
          - argo-workflows
        
        # Configuración simple sin persistencia de artefactos
        useDefaultArtifactRepo: false
        useStaticCredentials: false
        
        # Deshabilitar artefactos S3 para dev
        artifactRepository: {}
        
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-workflows
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
