apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      values: |
        # CONFIGURACIÓN MÍNIMA PARA DEV
        # Install CRDs automatically
        installCRDs: true

        # Webhook simplificado para dev
        webhook:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 32Mi

        # CA injector reducido para dev
        cainjector:
          resources:
            limits:
              cpu: 150m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 64Mi

        # Resources mínimos para controlador
        resources:
          limits:
            cpu: 150m
            memory: 128Mi
          requests:
            cpu: 25m
            memory: 64Mi
            
        # Deshabilitar métricas para dev
        prometheus:
          enabled: false
          
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
