apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.18.2
    helm:
      valueFiles:
        - values-dev/cert-manager-dev-values.yaml
      values: |
        # === MINIMAL DEVELOPMENT CONFIGURATION ===
        # Ref: https://cert-manager.io/docs/installation/helm/
        # Minimal setup with prometheus disabled for development
        
        crds:
          enabled: true
          keep: true
        
        controller:
          replicaCount: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        webhook:
          replicaCount: 1
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
        
        cainjector:
          enabled: true
          replicaCount: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # Disable prometheus for minimal setup
        prometheus:
          enabled: false
            
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
