apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: "9.3.1"
    helm:
      values: |
        # === CONFIGURACIÓN MÍNIMA PARA DESARROLLO ===
        
        adminUser: admin
        adminPassword: admin123
        
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        persistence:
          enabled: true
          size: 1Gi
        
        service:
          type: ClusterIP
          port: 80
        
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - grafana.local
        
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-stack-kube-prom-prometheus:9090
              access: proxy
              isDefault: true
            - name: Loki
              type: loki
              url: http://loki:3100
              access: proxy
        
        dashboards:
          default:
            kubernetes-cluster-monitoring:
              gnetId: 7249
              revision: 1
              datasource: Prometheus
        
        grafana.ini:
          server:
            root_url: http://grafana.local
          auth.anonymous:
            enabled: true
            org_role: Viewer
            
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
