apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 9.3.0
    helm:
      values: |
        # Configuración para acceso COMPLETAMENTE anónimo (sin login)
        grafana.ini:
          auth.anonymous:
            enabled: true
            org_name: "Organización Principal"
            org_role: Admin
            hide_version: false
          auth:
            disable_login_form: true
            disable_signout_menu: true
          security:
            allow_embedding: true
            disable_initial_admin_creation: true
          users:
            allow_sign_up: false
            allow_org_create: false
            viewers_can_edit: true
          dashboards:
            default_home_dashboard_path: ""
        
        # Sin persistencia para desarrollo
        persistence:
          enabled: false
        
        # Recursos mínimos para desarrollo
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        
        # ServiceMonitor deshabilitado
        serviceMonitor:
          enabled: false
        
        # Fuentes de datos
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-stack-kube-prom-prometheus.monitoring.svc.cluster.local:9090
              isDefault: true
              access: proxy
            - name: Loki
              type: loki
              url: http://loki-gateway.monitoring.svc.cluster.local
              access: proxy
        
        # Proveedores de dashboards
        dashboardProviders:
          dashboardproviders.yaml:
            apiVersion: 1
            providers:
            - name: 'default'
              orgId: 1
              folder: ''
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
        
        # Servicio
        service:
          type: ClusterIP
          port: 80
          
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
