apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.0
    helm:
      values: |
        controller:
          service:
            type: NodePort
            nodePorts:
              http: 30080
              https: 30443
          # Enable for minikube
          hostPort:
            enabled: false
          # Metrics deshabilitadas para desarrollo
          metrics:
            enabled: false
            serviceMonitor:
              enabled: false
          # Recursos mínimos para desarrollo
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # Additional configuration for development
          config:
            use-forwarded-headers: "true"
            compute-full-forwarded-for: "true"
        
        # Default backend simplificado
        defaultBackend:
          enabled: true
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
