apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: "3.4.1"
    helm:
      valueFiles:
        - values-dev/jaeger-dev-values.yaml
      values: |
        # === CONFIGURACIÓN MÍNIMA PARA DESARROLLO ===
        
        # All-in-one deployment para desarrollo
        allInOne:
          enabled: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
          securityContext:
            runAsUser: 10001
            runAsNonRoot: true
          
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: jaeger.local
                paths:
                  - path: /
                    pathType: Prefix
          
          # Configuración de memoria para desarrollo
          args:
            - --memory.max-traces=10000
        
        # Deshabilitar componentes separados
        agent:
          enabled: false
        collector:
          enabled: false
        query:
          enabled: false
        
        # Storage en memoria para desarrollo
        storage:
          type: memory
          
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
