apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Usando repositorio Git directo con chart oficial
    repoURL: https://github.com/akuity/kargo.git
    targetRevision: v1.6.2
    path: charts/kargo
    helm:
      valueFiles:
        - values-dev/kargo-dev-values.yaml
      values: |
        # === CONFIGURACIÓN MÍNIMA PARA DESARROLLO ===
        
        # API Server
        api:
          enabled: true
          replicas: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
          
          service:
            type: ClusterIP
            port: 80
          
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - host: kargo.local
                paths:
                  - path: /
                    pathType: Prefix
        
        # Controller
        controller:
          enabled: true
          replicas: 1
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
        
        # Webhook
        webhook:
          enabled: true
          replicas: 1
          resources:
            limits:
              cpu: 50m
              memory: 64Mi
            requests:
              cpu: 25m
              memory: 32Mi
          
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
