apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.min.io
    chart: minio
    targetRevision: 5.4.0
    helm:
      values: |
        # === TOY-SETUP FOR TESTING PURPOSES ===
        # Ref: https://github.com/minio/minio/tree/master/helm/minio
        # "Minimal toy setup for testing purposes"
        
        mode: standalone
        replicas: 1
        
        # Minimal resources for toy setup
        resources:
          requests:
            memory: 512Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m
        
        # Authentication for development
        auth:
          rootUser: minioadmin
          rootPassword: minioadmin123
        
        # No persistence for minimal toy setup
        persistence:
          enabled: false
        
        # Basic service configuration
        service:
          type: ClusterIP
          port: 9000
        
        # Simple ingress for dev access
        ingress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: minio.local
              paths:
                - path: /
                  pathType: Prefix
        
        # Console access for management
        consoleIngress:
          enabled: true
          ingressClassName: nginx
          hosts:
            - host: minio-console.local
              paths:
                - path: /
                  pathType: Prefix
        
        defaultBuckets: "bucket1,backup,artifacts"
        
        environment:
          MINIO_BROWSER_REDIRECT_URL: "http://minio-console.local"
          MINIO_SERVER_URL: "http://minio.local"
          
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
