apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.16.2
    helm:
      values: |
        # Install CRDs automatically
        crds:
          enabled: true
        
        # Enable Prometheus monitoring
        prometheus:
          enabled: true
          servicemonitor:
            enabled: true
        
        # Enable webhook for validation
        webhook:
          enabled: true
        
        # Enable cainjector for CA injection
        cainjector:
          enabled: true
        
        # Resources for development
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        
        # Webhook resources
        webhook:
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 64Mi
        
        # CA Injector resources  
        cainjector:
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 50m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
