apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-database
  namespace: demo-project
  labels:
    app: demo-database
    tier: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-database
  template:
    metadata:
      labels:
        app: demo-database
        tier: database
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command: ["redis-server"]
        args: 
        - "--appendonly"
        - "yes"
        - "--maxmemory"
        - "128mb"
        - "--maxmemory-policy"
        - "allkeys-lru"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /usr/local/etc/redis
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 128Mi
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: redis-data
        emptyDir: {}
      - name: redis-config
        configMap:
          name: demo-database-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-database-config
  namespace: demo-project
data:
  redis.conf: |
    # Redis configuration for demo
    bind 0.0.0.0
    port 6379
    timeout 300
    keepalive 60
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    appendonly yes
    appendfsync everysec
    
    # Logging
    loglevel notice
    
    # Development settings
    protected-mode no
    
    # Demo data initialization
    save 900 1
    save 300 10
    save 60 10000
---
apiVersion: v1
kind: Service
metadata:
  name: demo-database
  namespace: demo-project
  labels:
    app: demo-database
    tier: database
spec:
  selector:
    app: demo-database
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  type: ClusterIP
