apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-events
    targetRevision: 2.4.16
    helm:
      parameters:
        # Controller configuration
        - name: controller.replicas
          value: "1"
        - name: controller.resources.requests.memory
          value: "128Mi"
        - name: controller.resources.requests.cpu
          value: "100m"
        - name: controller.resources.limits.memory
          value: "256Mi"
        - name: controller.resources.limits.cpu
          value: "200m"
        
        # EventBus configuration (NATS-based for reliability)
        - name: configs.nats.versions[0].version
          value: "2.10.14"
        - name: configs.nats.versions[0].natsStreamingImage
          value: "nats-streaming:0.25.6"
        - name: configs.nats.versions[0].metricsExporterImage
          value: "natsio/prometheus-nats-exporter:0.15.0"
        
        # EventSource configuration  
        - name: configs.eventSourceExecutor.resources.requests.memory
          value: "64Mi"
        - name: configs.eventSourceExecutor.resources.requests.cpu
          value: "50m"
        - name: configs.eventSourceExecutor.resources.limits.memory
          value: "128Mi"
        - name: configs.eventSourceExecutor.resources.limits.cpu
          value: "100m"
        
        # Sensor configuration
        - name: configs.sensorExecutor.resources.requests.memory
          value: "64Mi"
        - name: configs.sensorExecutor.resources.requests.cpu
          value: "50m"
        - name: configs.sensorExecutor.resources.limits.memory
          value: "128Mi"
        - name: configs.sensorExecutor.resources.limits.cpu
          value: "100m"
        
      values: |
        # Global configuration
        global:
          image:
            tag: "v1.9.2"
        
        # RBAC permissions for GitOps integration
        rbac:
          enabled: true
        
        # Service Account
        serviceAccount:
          create: true
          name: argo-events
          annotations:
            argocd.argoproj.io/sync-wave: "1"
        
        # Controller specific settings
        controller:
          image:
            registry: quay.io
            repository: argoproj/argo-events
            tag: v1.9.2
          
          # Pod security context
          podSecurityContext:
            runAsNonRoot: true
            runAsUser: 9731
            fsGroup: 9731
          
          # Container security context  
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 9731
          
          # Health checks
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
          
          readinessProbe:
            httpGet:
              path: /readyz  
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
        
        # Webhook configuration for Gitea integration
        webhook:
          enabled: true
          service:
            type: ClusterIP
            port: 12000
          
        # EventBus configuration (NATS for production-ready event streaming)
        configs:
          # Default EventBus (NATS-based)
          eventBus:
            nats:
              native:
                # NATS configuration for reliable event streaming
                replicas: 1
                auth: none
                
                # Persistence for event durability
                persistence:
                  storageClass: standard
                  accessMode: ReadWriteOnce
                  volumeSize: 1Gi
                
                # Resource limits
                resources:
                  requests:
                    memory: "64Mi"
                    cpu: "50m"
                  limits:
                    memory: "128Mi" 
                    cpu: "100m"
                
                # Anti-affinity for high availability (when replicas > 1)
                affinity: {}
                
                # Monitoring
                metricsEnabled: true
                
        # Additional configurations for GitOps integration
        extraObjects:
          # Default EventBus for the namespace
          - apiVersion: argoproj.io/v1alpha1
            kind: EventBus
            metadata:
              name: default
              namespace: argo-events
            spec:
              nats:
                native:
                  replicas: 1
                  auth: none
                  persistence:
                    storageClass: standard
                    accessMode: ReadWriteOnce
                    volumeSize: 1Gi
                  metricsEnabled: true
                  resources:
                    requests:
                      memory: "64Mi"
                      cpu: "50m"
                    limits:
                      memory: "128Mi"
                      cpu: "100m"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  revisionHistoryLimit: 3
