apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-project
  namespace: argocd
  labels:
    project: demo-project
spec:
  project: default
  source:
    repoURL: http://gitea-service/your-user/your-repo.git # CAMBIAR: URL del repositorio Gitea local
    targetRevision: HEAD
    path: projects/demo-project/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
