apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: "PrunePropagationPolicy=foreground"
spec:
  project: default
  source:
    repoURL: https://github.com/andres20980/gh-gitops-infra.git
    targetRevision: HEAD
    path: components/gitea
    directory:
      include: "*-pvc.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
