apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    # Usando repositorio Git directo con chart oficial
    repoURL: https://github.com/akuity/kargo.git
    targetRevision: v1.6.2
    path: charts/kargo
    helm:
      valueFiles:
  - values-dev/kargo-dev-values.yaml
          
  destination:
    server: https://kubernetes.default.svc
    namespace: kargo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
