apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-rollouts
    targetRevision: 2.40.2  # Chart version correcta (app version v1.8.3)
    helm:
      values: |
        # Configuración del controlador
        controller:
          replicas: 1
          
        # Habilitar dashboard sin autenticación
        dashboard:
          enabled: true
          readonly: false
          service:
            type: ClusterIP
            port: 3100
          # Sin autenticación para desarrollo
          config:
            auth:
              enabled: false
            
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts
  # Add this block to ignore the specific, harmless difference in the CRDs.
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
