apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-simple
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 20.2.1
    helm:
      values: |
        auth:
          enabled: false
        master:
          persistence:
            enabled: false
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"  
              cpu: "100m"
        replica:
          replicaCount: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: simple-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
