name: Shellcheck

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: |
          find . -type f -name '*.sh' -print0 | xargs -0 shellcheck || true
      - name: Show summary
        run: echo "Shellcheck finished"
