apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: herramientas-gitops
  namespace: argocd
  labels:
    app.kubernetes.io/name: herramientas-gitops
    app.kubernetes.io/component: gitops-infrastructure
spec:
  project: default
  source:
    repoURL: https://github.com/asanchez-dev/gh-gitops-infra
    targetRevision: HEAD
    path: herramientas-gitops
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
